### ISSUE TITLE
Remove empty elements from BnF items

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-metadata/metadata-remediation#11]
https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Agj309bn0813

**Comment by arcadiafalcone** [comment]
Also fix cataloging language

**Comment by cebraj** [comment]
I can take a look at these. I remember Ben Albritton said this is very old content and the metadata was mapped from TEI so he wasn't surprised that there'd be some issues...

**Comment by cebraj** [comment]
Fixed!
