### ISSUE TITLE
Fix subject authority in Latvian oral history collection

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-metadata/metadata-remediation#13]
https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Anf604rk4389

authority="Icsh" (capital i instead of l)

**Comment by arcadiafalcone** [comment]
See also #37

**Comment by cebraj** [comment]
These should all be fixed now :)
