### ISSUE TITLE
Fix broken subject metadata in Keith Johnstone papers

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-metadata/metadata-remediation#15]
https://argo.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=Keith+Johnstone+Papers

**Comment by cebraj** [comment]
@arcadiafalcone do you recall what was wrong with the subjects? I don't see anything amiss at first glance. Oh! I see some weirdness in the collection-level object. Was that it?

**Comment by arcadiafalcone** [comment]
I think I fixed these and forgot to close the ticket! But I don't think I checked the collection object - please do take a look at that and close the ticket when it's OK.

**Comment by cebraj** [comment]
Ok cool! I refreshed the MODS on the collection object and it looks much better now. It hadn't been refreshed since 2013!
