### ISSUE TITLE
Add role authority attributes to MARL records

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-metadata/metadata-remediation#48]
For code values, an authority should be present to show the source of the code.

https://argo.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=Musical+Acoustics+Research+Library

**Comment by cebraj** [comment]
will look at these since i've been uploading the metadata. i thought Herve included 'marcrelator' but maybe it was missed.

**Comment by cebraj** [comment]
Fixed! There was one set where "marcrelator" was in the first row but then it didn't get dragged down to all rows.
