### ISSUE TITLE
Fix records with frequency at top level that use the digital serials model

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-metadata/metadata-remediation#54]
The `frequency` element should be moved so that it is inside `originInfo`.

ckey: 397421
APO: druid:wt950sc9924
items
druid:gc306kb3630
druid:yj281wd8708
druid:pc824hb1962
druid:hm256dz1461
druid:ry416vn4307
druid:wp171dz5837
druid:xb709dd7427
druid:yh182dg5205
druid:xv973dm9526
druid:br701rd9424
druid:vb153zc8244

ckey: 9100313
APO: druid:jj305hm5259
items:
druid:xm252pn4140
druid:tx066sr4275

**Comment by cebraj** [comment]
Fixed!
